# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'TIL by Nico'
tagline:          'Learning something new everyday' 
description:      'A blog dedicated to everyday learnings, ramblings, and musings.'
url:              'https://nmenego.github.io/'
baseurl:          'https://nmenego.github.io/'

author:
  name:           'Nico Martin EÃ±ego'
  url:            'https://www.linkedin.com/in/nmenego/'

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/nmenego/nmenego.github.io
