# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'TIL by Nico'
tagline:          'Learning something new everyday' 
description:      'A blog dedicated to everyday learnings and musings.'
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed  # Used for Sitemap.xml and your RSS feed
url:              

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:          '/nmenego.github.io'

author:
  name:           'Nico Martin EÃ±ego'
  url:            https://www.linkedin.com/in/nmenego/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nmenego/nmenego.github.io
